export const KNOWN_ACTIONS = [
  'login.success',
  'login.failure',
  'login.locked',
  'logout',
  'password.change',
  'email.change',
  'session.revoke',
  'session.revoke_all',
  'profile.update',
  'project.create',
  'project.update',
  'project.delete',
  'experience.create',
  'experience.update',
  'experience.delete',
  'honor.create',
  'honor.update',
  'honor.delete',
] as const;
